apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app
  name: my-service
spec:
  ports:
  - name: webports
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
#    env: pre
  type: ClusterIP
